<?php

namespace AppBundle\Repository;

/**
 * OccasionalTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccasionalTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
